version: '3.0'
services:
  elk:
    image: sebp/elk
    container_name: alfabank-service-elk-prod
    ports:
      - "5601:5601"

  service:
    image: alfabank-service
    container_name: alfabank-service-prod
    depends_on:
      - elk
    links:
      - elk
    ports:
      - "5001:5000"
    volumes:
      - /tmp/alfabank-service-logs:/app/logs

  cli:
    image: alfabank-service-cli
    container_name: alfabank-service-cli-prod
    depends_on:
      - service
    ports:
      - "3000:3000"